### ISSUE TITLE
Allow using the global quickfix window

### ISSUE THREAD

**Issue by AndrewRadev** [elbeardmorez/vim-loclist-follow#2]
By default, I tend to use the global quickfix window rather than the location list. I can see the case for either, so I'm wondering if it'd be possible to add support to the plugin for both cases.

A quick test shows that replacing `getloclist` with `getqflist` and `ll` with `cc` seems to work just fine. But in order to make both work, I'd guess there needs to be another set of autocommands, maybe something like:

``` vim
if bv
    execute "autocmd loclist_follow CursorMoved <buffer=" . bufnr('') . "> call s:LoclistNearest('local', " . bufnr('') . ")"
    execute "autocmd loclist_follow CursorMoved <buffer=" . bufnr('') . "> call s:LoclistNearest('global', " . bufnr('') . ")"
else
    autocmd! loclist_follow CursorMoved <buffer>
endif
```

And then the `s:LoclistNearest` function could call a different function depending on its parameter, updating both location and quickfix list.

I'm pretty sure it'd be good to add some settings for the "global"/"quickfix" scenario, if you decide to implement it, so I won't open a PR for the moment -- let me know what you think of the idea first.

**Comment by elbeardmorez** [comment]
Implemented verbatim and credited. Thanks for this, it was in my mind, but I wouldn't have done it unless asked ..which is to my detriment, as I think I'll use the quickfix list exclusively now!

**Comment by AndrewRadev** [comment]
Awesome, thanks, seems to work just fine for me!
